// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rafaelcoelhox/labbend/internal/challenges (interfaces: EventBus)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	eventbus "github.com/rafaelcoelhox/labbend/internal/core/eventbus"
)

// MockChallengesEventBus is a mock of EventBus interface.
type MockChallengesEventBus struct {
	ctrl     *gomock.Controller
	recorder *MockChallengesEventBusMockRecorder
}

// MockChallengesEventBusMockRecorder is the mock recorder for MockChallengesEventBus.
type MockChallengesEventBusMockRecorder struct {
	mock *MockChallengesEventBus
}

// NewMockChallengesEventBus creates a new mock instance.
func NewMockChallengesEventBus(ctrl *gomock.Controller) *MockChallengesEventBus {
	mock := &MockChallengesEventBus{ctrl: ctrl}
	mock.recorder = &MockChallengesEventBusMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChallengesEventBus) EXPECT() *MockChallengesEventBusMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockChallengesEventBus) Publish(arg0 eventbus.Event) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Publish", arg0)
}

// Publish indicates an expected call of Publish.
func (mr *MockChallengesEventBusMockRecorder) Publish(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockChallengesEventBus)(nil).Publish), arg0)
}
