// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rafaelcoelhox/labbend/internal/challenges (interfaces: EventBus)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	eventbus "github.com/rafaelcoelhox/labbend/pkg/eventbus"
	gorm "gorm.io/gorm"
)

// MockChallengesEventBus is a mock of EventBus interface.
type MockChallengesEventBus struct {
	ctrl     *gomock.Controller
	recorder *MockChallengesEventBusMockRecorder
}

// MockChallengesEventBusMockRecorder is the mock recorder for MockChallengesEventBus.
type MockChallengesEventBusMockRecorder struct {
	mock *MockChallengesEventBus
}

// NewMockChallengesEventBus creates a new mock instance.
func NewMockChallengesEventBus(ctrl *gomock.Controller) *MockChallengesEventBus {
	mock := &MockChallengesEventBus{ctrl: ctrl}
	mock.recorder = &MockChallengesEventBusMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChallengesEventBus) EXPECT() *MockChallengesEventBusMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockChallengesEventBus) Publish(arg0 eventbus.Event) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Publish", arg0)
}

// Publish indicates an expected call of Publish.
func (mr *MockChallengesEventBusMockRecorder) Publish(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockChallengesEventBus)(nil).Publish), arg0)
}

// PublishWithTx mocks base method.
func (m *MockChallengesEventBus) PublishWithTx(arg0 context.Context, arg1 *gorm.DB, arg2 eventbus.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishWithTx", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishWithTx indicates an expected call of PublishWithTx.
func (mr *MockChallengesEventBusMockRecorder) PublishWithTx(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishWithTx", reflect.TypeOf((*MockChallengesEventBus)(nil).PublishWithTx), arg0, arg1, arg2)
}
