# fly.toml app configuration file generated for labend on 2024-01-01
app = "labend"
primary_region = "gru"  # São Paulo, Brazil - ou "sjc" para São Jose dos Campos

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  GO_ENV = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 800

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[checks]
  [checks.health]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    path = "/health"
    port = 8080
    timeout = "5s"
    type = "http"
    headers = {}

[deploy]
  release_command = "echo 'Deployment completed'"
  strategy = "rolling"

# Configurações de banco de dados (PostgreSQL no Fly.io)
[mounts]
  source = "labend_data"
  destination = "/data" 