run:
  timeout: 5m
  go: "1.23"
  skip-dirs:
    - bin
    - scripts
    - vendor
  skip-files:
    - ".*\\.pb\\.go$"
    - ".*_mock\\.go$"

linters:
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - exportloopref
    - funlen
    - gci
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomnd
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - makezero
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

linters-settings:
  funlen:
    lines: 100
    statements: 50
  
  gocognit:
    min-complexity: 20
    
  gocyclo:
    min-complexity: 20
    
  goconst:
    min-len: 3
    min-occurrences: 3
    
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
      
  gofmt:
    simplify: true
    
  goimports:
    local-prefixes: github.com/rafaelcoelhox/labbend
    
  gomnd:
    checks: argument,case,condition,return
    
  lll:
    line-length: 120
    
  misspell:
    locale: US
    
  nolintlint:
    allow-leading-space: true
    allow-unused: false
    require-explanation: false
    require-specific: false

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - funlen
        - gocognit
        - gocyclo
        - lll
    - path: internal/mocks/
      linters:
        - gomnd
        - funlen
        - gocognit
        - gocyclo
        - lll
        - unused
    - path: cmd/
      linters:
        - gomnd
  
  max-issues-per-linter: 0
  max-same-issues: 0 