version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: labend-postgres
    environment:
      POSTGRES_USER: labend_user
      POSTGRES_PASSWORD: labend_password
      POSTGRES_DB: labend_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U labend_user -d labend_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: labend-app
    environment:
      - PORT=8080
      - DATABASE_URL=postgres://labend_user:labend_password@postgres:5432/labend_db?sslmode=disable
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data: