version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: labend-postgres
    environment:
      POSTGRES_USER: labend_user
      POSTGRES_PASSWORD: labend_password
      POSTGRES_DB: labend_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/configs/postgres/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U labend_user -d labend_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: 
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: labend-app
    environment:
      - PORT=8080
      - DATABASE_URL=postgres://labend_user:labend_password@postgres:5432/labend_db?sslmode=disable
      - LOG_LEVEL=debug
      - ENVIRONMENT=development
      - METRICS_ENABLED=true
    ports:
      - "8081:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data: 