# fly.staging.toml app configuration file for staging environment
app = "labend-staging"
primary_region = "gru"  # São Paulo, Brazil

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  GO_ENV = "staging"
  LOG_LEVEL = "debug"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 500
    soft_limit = 400

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1

[checks]
  [checks.health]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    path = "/health"
    port = 8080
    timeout = "5s"
    type = "http"
    headers = {}

[deploy]
  release_command = "echo 'Staging deployment completed'"
  strategy = "immediate"

# Configurações de banco de dados para staging
[mounts]
  source = "labend_staging_data"
  destination = "/data" 