groups:
  - name: labend-performance
    rules:
      # Goroutine Leak Detection
      - alert: HighGoroutineCount
        expr: go_goroutines_total > 1000
        for: 2m
        labels:
          severity: warning
          component: goroutines
        annotations:
          summary: "Alto número de goroutines detectado"
          description: "Aplicação {{ $labels.instance }} tem {{ $value }} goroutines (threshold: 1000)"

      - alert: GoroutineLeakDetected
        expr: increase(go_goroutines_total[5m]) > 500
        for: 1m
        labels:
          severity: critical
          component: goroutines
        annotations:
          summary: "Possível vazamento de goroutines"
          description: "Aplicação {{ $labels.instance }} teve aumento de {{ $value }} goroutines em 5 minutos"

      # Memory Leak Detection
      - alert: HighMemoryUsage
        expr: go_heap_memory_bytes / 1024 / 1024 > 500
        for: 5m
        labels:
          severity: warning
          component: memory
        annotations:
          summary: "Alto uso de memória heap"
          description: "Aplicação {{ $labels.instance }} está usando {{ $value }}MB de heap (threshold: 500MB)"

      - alert: MemoryLeakDetected
        expr: increase(go_heap_memory_bytes[10m]) > 104857600  # 100MB
        for: 2m
        labels:
          severity: critical
          component: memory
        annotations:
          summary: "Possível vazamento de memória"
          description: "Heap da aplicação {{ $labels.instance }} cresceu {{ $value | humanize1024 }} em 10 minutos"

      - alert: MemoryLeakAlertTriggered
        expr: increase(memory_leak_alerts_total[5m]) > 0
        for: 0m
        labels:
          severity: critical
          component: memory
        annotations:
          summary: "Alerta de vazamento de memória disparado"
          description: "Aplicação {{ $labels.instance }} detectou {{ $value }} vazamentos de memória"

      # Race Condition Detection
      - alert: RaceConditionDetected
        expr: increase(race_condition_alerts_total[1m]) > 0
        for: 0m
        labels:
          severity: critical
          component: concurrency
        annotations:
          summary: "Race condition detectada"
          description: "Aplicação {{ $labels.instance }} detectou {{ $value }} race conditions"

      # CPU Usage
      - alert: HighCPUUsage
        expr: go_cpu_usage_percent > 80
        for: 5m
        labels:
          severity: warning
          component: cpu
        annotations:
          summary: "Alto uso de CPU"
          description: "Aplicação {{ $labels.instance }} está usando {{ $value }}% de CPU"

      - alert: CriticalCPUUsage
        expr: go_cpu_usage_percent > 95
        for: 2m
        labels:
          severity: critical
          component: cpu
        annotations:
          summary: "Uso crítico de CPU"
          description: "Aplicação {{ $labels.instance }} está usando {{ $value }}% de CPU"

      # Garbage Collection
      - alert: HighGCFrequency
        expr: rate(go_gc_duration_seconds_count[5m]) > 2
        for: 2m
        labels:
          severity: warning
          component: gc
        annotations:
          summary: "Alta frequência de garbage collection"
          description: "Aplicação {{ $labels.instance }} está executando GC {{ $value }} vezes por segundo"

      - alert: LongGCPauses
        expr: histogram_quantile(0.99, rate(go_gc_duration_seconds_bucket[5m])) > 0.1
        for: 2m
        labels:
          severity: warning
          component: gc
        annotations:
          summary: "Pausas longas no garbage collection"
          description: "99% das pausas de GC na aplicação {{ $labels.instance }} estão acima de {{ $value }}s"

      # Heap Objects
      - alert: HighHeapObjectCount
        expr: go_heap_objects_total > 1000000
        for: 5m
        labels:
          severity: warning
          component: heap
        annotations:
          summary: "Alto número de objetos no heap"
          description: "Aplicação {{ $labels.instance }} tem {{ $value }} objetos no heap"

      # Database Connection Pool
      - alert: HighDatabaseConnections
        expr: pg_stat_database_numbackends > 80
        for: 2m
        labels:
          severity: warning
          component: database
        annotations:
          summary: "Alto número de conexões no banco"
          description: "Banco {{ $labels.instance }} tem {{ $value }} conexões ativas"

      # Application Availability
      - alert: ApplicationDown
        expr: up{job="labend-app"} == 0
        for: 1m
        labels:
          severity: critical
          component: availability
        annotations:
          summary: "Aplicação LabEnd está indisponível"
          description: "Aplicação {{ $labels.instance }} não está respondendo"

      # HTTP Error Rate
      - alert: HighErrorRate
        expr: rate(http_requests_total{code=~"5.."}[5m]) > 0.1
        for: 2m
        labels:
          severity: warning
          component: http
        annotations:
          summary: "Alta taxa de erros HTTP"
          description: "Aplicação {{ $labels.instance }} tem {{ $value }} erros 5xx por segundo"

  - name: labend-outbox
    rules:
      # Outbox Event Monitoring
      - alert: OutboxEventsStuck
        expr: outbox_pending_events > 100
        for: 5m
        labels:
          severity: warning
          component: outbox
        annotations:
          summary: "Eventos pendentes no outbox"
          description: "Aplicação {{ $labels.instance }} tem {{ $value }} eventos pendentes no outbox"

      - alert: OutboxEventsFailed
        expr: outbox_failed_events > 10
        for: 2m
        labels:
          severity: critical
          component: outbox
        annotations:
          summary: "Eventos falharam no outbox"
          description: "Aplicação {{ $labels.instance }} tem {{ $value }} eventos falhados no outbox"

  - name: labend-saga
    rules:
      # Saga Monitoring
      - alert: SagasStuck
        expr: saga_running_count > 10
        for: 10m
        labels:
          severity: warning
          component: saga
        annotations:
          summary: "Muitas sagas em execução"
          description: "Aplicação {{ $labels.instance }} tem {{ $value }} sagas rodando há mais de 10 minutos"

  - name: system-resources
    rules:
      # System CPU
      - alert: HighSystemCPU
        expr: 100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
          component: system
        annotations:
          summary: "Alto uso de CPU do sistema"
          description: "Sistema {{ $labels.instance }} está usando {{ $value }}% de CPU"

      # System Memory
      - alert: HighSystemMemory
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 80
        for: 5m
        labels:
          severity: warning
          component: system
        annotations:
          summary: "Alto uso de memória do sistema"
          description: "Sistema {{ $labels.instance }} está usando {{ $value }}% de memória"

      # Disk Usage
      - alert: HighDiskUsage
        expr: (1 - (node_filesystem_avail_bytes / node_filesystem_size_bytes)) * 100 > 80
        for: 5m
        labels:
          severity: warning
          component: disk
        annotations:
          summary: "Alto uso de disco"
          description: "Sistema {{ $labels.instance }} está usando {{ $value }}% do disco"

      # Container Resources
      - alert: HighContainerMemory
        expr: (container_memory_usage_bytes / container_spec_memory_limit_bytes) * 100 > 80
        for: 5m
        labels:
          severity: warning
          component: container
        annotations:
          summary: "Alto uso de memória do container"
          description: "Container {{ $labels.name }} está usando {{ $value }}% de memória"

      - alert: HighContainerCPU
        expr: (rate(container_cpu_usage_seconds_total[5m]) * 100) > 80
        for: 5m
        labels:
          severity: warning
          component: container
        annotations:
          summary: "Alto uso de CPU do container"
          description: "Container {{ $labels.name }} está usando {{ $value }}% de CPU" 